name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build:frontend --if-present
    - run: npm run build:backend --if-present
    - run: npm run bundle --if-present
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: bundled-app
        path: bundle
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: download artifacts
      uses: actions/download-artifact@master
      with:
        name: bundled-app
        path: bundle
    - run: ls -la
    - name: copy files via ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "bundle/*"
        target: "/var/www/urfu-ui.len0xx.ru"
